/** The ten roles the Users & Roles sheet defines. */
module.exports = [
  {
    name: 'Owner / Super admin',
    department: 'Management',
    reportsTo: '—',
    dashboard: 'Business overview',
    scope: 'all',
    superAdmin: true,
    modules: ['CRM', 'Membership', 'Booking', 'Finance', 'Customer', 'Inventory', 'Vendors', 'WhatsApp', 'Reports', 'Users'],
    permissions: ['view', 'create', 'edit', 'delete', 'approve', 'financial', 'export', 'assign'],
    approvals: ['Membership', 'Refund', 'Discount', 'Payment'],
  },
  {
    name: 'Business head',
    department: 'Management',
    reportsTo: 'Owner / Super admin',
    dashboard: 'Business overview',
    scope: 'all',
    modules: ['CRM', 'Membership', 'Booking', 'Finance', 'Customer', 'WhatsApp', 'Reports', 'Users'],
    permissions: ['view', 'create', 'edit', 'approve', 'financial', 'export', 'assign'],
    approvals: ['Membership', 'Refund', 'Discount'],
  },
  {
    name: 'Branch business manager',
    department: 'Sales',
    reportsTo: 'Business head',
    dashboard: 'Sales dashboard',
    scope: 'branch',
    modules: ['CRM', 'Membership', 'Booking', 'Customer', 'WhatsApp', 'Reports'],
    permissions: ['view', 'create', 'edit', 'approve', 'export', 'assign'],
    approvals: ['Membership', 'Discount'],
  },
  {
    name: 'Assistant branch manager',
    department: 'Sales',
    reportsTo: 'Branch business manager',
    dashboard: 'Sales dashboard',
    scope: 'team',
    modules: ['CRM', 'Membership', 'Booking', 'Customer', 'WhatsApp'],
    permissions: ['view', 'create', 'edit', 'assign'],
    approvals: ['Discount'],
  },
  {
    name: 'Sales head',
    department: 'Sales',
    reportsTo: 'Business head',
    dashboard: 'Sales dashboard',
    scope: 'all',
    modules: ['CRM', 'Membership', 'Booking', 'Customer', 'Reports'],
    permissions: ['view', 'create', 'edit', 'approve', 'export', 'assign'],
    approvals: ['Discount'],
  },
  {
    name: 'Travel expert',
    department: 'Sales',
    reportsTo: 'Assistant branch manager',
    dashboard: 'My sales dashboard',
    scope: 'own',
    modules: ['CRM', 'Membership', 'Booking', 'Customer', 'WhatsApp'],
    permissions: ['view', 'create', 'edit'],
    approvals: [],
  },
  {
    name: 'Field officer',
    department: 'Field team',
    reportsTo: 'Travel expert',
    dashboard: 'My sales dashboard',
    scope: 'own',
    modules: ['CRM', 'Customer'],
    permissions: ['view', 'edit'],
    approvals: [],
  },
  {
    name: 'Operations manager',
    department: 'Operations',
    reportsTo: 'Business head',
    dashboard: 'Booking dashboard',
    scope: 'all',
    modules: ['Booking', 'Inventory', 'Vendors', 'Customer', 'Reports'],
    permissions: ['view', 'create', 'edit', 'approve', 'export', 'assign'],
    approvals: ['Membership'],
  },
  {
    name: 'Finance',
    department: 'Accounts',
    reportsTo: 'Business head',
    dashboard: 'Finance dashboard',
    scope: 'all',
    modules: ['Finance', 'Booking', 'Membership', 'Reports'],
    permissions: ['view', 'edit', 'approve', 'financial', 'export'],
    approvals: ['Refund', 'Payment'],
  },
  {
    name: 'Support executive',
    department: 'Support',
    reportsTo: 'Operations manager',
    dashboard: 'My sales dashboard',
    scope: 'team',
    modules: ['Customer', 'Booking', 'WhatsApp'],
    permissions: ['view', 'create', 'edit'],
    approvals: [],
  },
];
