/** Every model in one place, so a controller or a script imports once. */
module.exports = {
  Approval: require('./Approval'),
  AuditLog: require('./AuditLog'),
  AutomationRule: require('./AutomationRule'),
  BotFlow: require('./BotFlow'),
  Booking: require('./Booking'),
  Campaign: require('./Campaign'),
  Conversation: require('./Conversation'),
  Counter: require('./Counter'),
  Customer: require('./Customer'),
  Expense: require('./Expense'),
  Hold: require('./Hold'),
  InventoryItem: require('./InventoryItem'),
  Invoice: require('./Invoice'),
  Lead: require('./Lead'),
  Membership: require('./Membership'),
  MembershipPlan: require('./MembershipPlan'),
  Offer: require('./Offer'),
  Partner: require('./Partner'),
  Payment: require('./Payment'),
  Referral: require('./Referral'),
  Refund: require('./Refund'),
  Reward: require('./Reward'),
  Role: require('./Role'),
  Task: require('./Task'),
  Ticket: require('./Ticket'),
  User: require('./User'),
};
